### ISSUE TITLE
Dev start error "Invalid host defined options"

### ISSUE THREAD

**Issue by Nikoxx99** [harlan-zw/nuxt-build-optimisations#35]
Just updated from nuxt-build-optimisation to nuxt-webpack-optimisations, followed the migration guide, uninstalled the old one, installed the new version, remove node_modules/.cache, copy the suggested config to nuxt.config.js but it does not run.

My package.json dep list

"dependencies": {
    "@nuxtjs/apollo": "^4.0.1-rc.5",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/strapi": "^0.3.1",
    "cookieparser": "^0.1.0",
    "cross-env": "^5.2.0",
    "graphql-tag": "^2.12.4",
    "js-cookie": "^2.2.1",
    "nuxt": "^2.15.4",
    "nuxt-i18n": "^6.27.0",
    "nuxt-webpack-optimisations": "^2.0.3",
    "quagga": "^0.12.1"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/vuetify": "^1.11.3",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.25.0",
    "eslint-plugin-nuxt": "^1.0.0"
  }

And when i run "npm run dev" this error appears.
 FATAL  Invalid host defined options                                                                                                                                                                                           10:00:07  

  at ModuleContainer.module.exports (node_modules\nuxt-webpack-optimisations\module.cjs:3:3)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:34)
  at node_modules\@nuxt\utils\dist\utils.js:639:43
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)

**Comment by harlan-zw** [comment]
Hey @Nikoxx99 

I did come across this one as well, it's very strange. I wasn't able to dig into what the exact issue is, it seems like it's a problem with one of the locked dependencies. If you delete node_modules and re-install it may fix it, otherwise a very hacky solution that I found worked was removing the lock file and re-install the dependencies.

I'll keep looking into it if I can figure out a non-manual way to solve it

**Comment by cocolee** [comment]
hi @harlan-zw 
first of all thanks for the plugin. I tried to delete node_modules and install again it's getting the same error 'Invalid host defined options'.

**Comment by testn** [comment]
I'm getting the same error as well.

**Comment by itsmnthn** [comment]
I'm getting the same error

**Comment by andorfermichael** [comment]
same issue, but deleting the lock file is no option as this could (and will in my case) break the whole application.
